services:
  # Service de la base de données
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=jobgatedb
      - POSTGRES_USER=jobgateuser
      - POSTGRES_PASSWORD=jobgatepass
    # Optimisations pour accélérer démarrage PostgreSQL
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-jobgateuser} -d ${POSTGRES_DB:-jobgatedb}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Service Backend Django
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "./wait-for-db.sh db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app  # Synchronise le code en direct
      # Éviter de synchroniser les fichiers cache et autres
      - /app/node_modules
      - /app/__pycache__
      - /app/*.pyc
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=jobgatedb
      - POSTGRES_USER=jobgateuser
      - POSTGRES_PASSWORD=jobgatepass
      - POSTGRES_HOST=db
      # Variable pour signaler que nous sommes en environnement Docker
      - DOCKER_ENVIRONMENT=1
      # Email via MailHog en développement
      - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
      - EMAIL_USE_TLS=false
      - EMAIL_USE_SSL=false
      - DEFAULT_FROM_EMAIL=no-reply@jobgate.local
      - FRONTEND_BASE_URL=http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Service Frontend React
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app # Synchronise le code en direct
      # Éviter de synchroniser les fichiers node_modules
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true # Active le hot-reload de React dans Docker
      # Variables pour améliorer les performances de Node.js
      - NODE_ENV=development
    depends_on:
      backend:
        condition: service_started

  # MailHog - Capture et visualisation des emails en dev
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # UI Web

volumes:
  postgres_data: