version: '3.8'

services:
  # Service de la base de données
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=jobgatedb
      - POSTGRES_USER=jobgateuser
      - POSTGRES_PASSWORD=jobgatepass

  # Service Backend Django
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app  # Synchronise le code en direct
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=jobgatedb
      - POSTGRES_USER=jobgateuser
      - POSTGRES_PASSWORD=jobgatepass
      - POSTGRES_HOST=db  # IMPORTANT: 'db' est le nom du service PostgreSQL
    depends_on:
      - db # S'assure que la BDD démarre avant le backend

  # Service Frontend React
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app # Synchronise le code en direct
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true # Active le hot-reload de React dans Docker

volumes:
  postgres_data: