version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: jobgate_db
      POSTGRES_USER: jobgate_user
      POSTGRES_PASSWORD: jobgate_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jobgate_user -d jobgate_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.full-ai
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://jobgate_user:jobgate_password@db:5432/jobgate_db
    depends_on:
      db:
        condition: service_healthy
    # Augmenter les ressources pour les dépendances IA
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data:
