# Generated by Django 5.2.5 on 2025-08-09 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Titre de l'offre")),
                ('description', models.TextField(verbose_name='Description du poste')),
                ('location', models.CharField(max_length=150, verbose_name='Lieu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre de la campagne')),
                ('submission_deadline', models.DateField(verbose_name='Date limite de soumission')),
                ('job_offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview_campaign', to='JobsInterview.joboffer', verbose_name="Offre d'emploi associée")),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texte de la question')),
                ('preparation_time', models.PositiveIntegerField(default=30, verbose_name='Temps de préparation (secondes)')),
                ('response_duration_limit', models.PositiveIntegerField(default=180, verbose_name='Temps de réponse maximum (secondes)')),
                ('order', models.PositiveIntegerField(verbose_name='Ordre de la question')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='JobsInterview.interviewcampaign', verbose_name='Campagne associée')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('campaign', 'order')},
            },
        ),
    ]
