# Generated by Django 5.2.5 on 2025-08-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='contract_type',
            field=models.CharField(choices=[('CDI', 'Contrat à Durée Indéterminée'), ('CDD', 'Contrat à Durée Déterminée'), ('STAGE', 'Stage'), ('ALTERNANCE', 'Alternance'), ('FREELANCE', 'Freelance'), ('INTERIM', 'Intérim')], default='CDI', max_length=20, verbose_name='Type de contrat'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='prerequisites',
            field=models.TextField(blank=True, null=True, verbose_name='Prérequis'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='salary',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Salaire'),
        ),
    ]
