# Generated by Django 5.2.5 on 2025-08-23 15:43

import django.db.models.deletion
import interviews.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_jobapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email destinataire')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Token')),
                ('expires_at', models.DateTimeField(default=interviews.models.default_link_expiration, verbose_name='Expire le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Utilisé le')),
                ('max_uses', models.PositiveIntegerField(default=1, verbose_name="Nombre d'usages autorisés")),
                ('uses_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'usages consommés")),
                ('revoked', models.BooleanField(default=False, verbose_name='Révoqué')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='interviews.interviewcampaign', verbose_name='Campagne')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_links', to=settings.AUTH_USER_MODEL, verbose_name='Candidat')),
            ],
            options={
                'verbose_name': 'Lien de campagne',
                'verbose_name_plural': 'Liens de campagne',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('uses_count__gte', 0)), name='campaignlink_uses_count_gte_0'), models.CheckConstraint(condition=models.Q(('max_uses__gte', 1)), name='campaignlink_max_uses_gte_1')],
            },
        ),
    ]
