# Generated by Django 5.2.5 on 2025-08-23 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_campaignlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='campaignlink',
            constraint=models.UniqueConstraint(condition=models.Q(('candidate__isnull', False)), fields=('campaign', 'candidate'), name='unique_link_per_campaign_and_candidate'),
        ),
        migrations.AddConstraint(
            model_name='campaignlink',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('campaign', 'email'), name='unique_link_per_campaign_and_email'),
        ),
    ]
