# Generated by Django 5.2.5 on 2025-08-26 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_campaignlink_unique_link_per_campaign_and_candidate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(help_text='Réponse vidéo du candidat', upload_to='interview_answers/%Y/%m/%d/', verbose_name='Fichier vidéo')),
                ('duration', models.PositiveIntegerField(help_text="Durée de l'enregistrement en secondes", verbose_name='Durée (secondes)')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille du fichier (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('completed', 'Terminée'), ('failed', 'Échec')], default='pending', max_length=20, verbose_name='Statut')),
                ('recruiter_notes', models.TextField(blank=True, null=True, verbose_name='Notes du recruteur')),
                ('score', models.PositiveIntegerField(blank=True, help_text='Score sur 100', null=True, verbose_name='Score')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_answers', to=settings.AUTH_USER_MODEL, verbose_name='Candidat')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='interviews.interviewquestion', verbose_name='Question')),
            ],
            options={
                'verbose_name': "Réponse d'entretien",
                'verbose_name_plural': "Réponses d'entretien",
                'ordering': ['-created_at'],
                'unique_together': {('question', 'candidate')},
            },
        ),
    ]
