# Generated by Django 5.2.5 on 2025-08-26 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_interviewanswer'),
    ]

    operations = [
    ]
