# Generated by Django 5.2.5 on 2025-09-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0007_auto_20250826_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, help_text='ID public de la vidéo sur Cloudinary', max_length=255, null=True, verbose_name='Cloudinary Public ID'),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='cloudinary_secure_url',
            field=models.URLField(blank=True, help_text='URL HTTPS de la vidéo sur Cloudinary', null=True, verbose_name='URL sécurisée Cloudinary'),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='cloudinary_url',
            field=models.URLField(blank=True, help_text='URL de la vidéo sur Cloudinary', null=True, verbose_name='URL Cloudinary'),
        ),
    ]
