# Generated by Django 5.2.5 on 2025-09-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0008_interviewanswer_cloudinary_public_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewanswer',
            name='cloudinary_public_id',
        ),
        migrations.RemoveField(
            model_name='interviewanswer',
            name='cloudinary_secure_url',
        ),
        migrations.RemoveField(
            model_name='interviewanswer',
            name='cloudinary_url',
        ),
    ]
