# Generated by Django 5.2.5 on 2025-09-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0009_remove_interviewanswer_cloudinary_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewanswer',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cloudinary Public ID'),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='cloudinary_secure_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='Cloudinary Secure URL'),
        ),
        migrations.AddField(
            model_name='interviewanswer',
            name='cloudinary_url',
            field=models.URLField(blank=True, max_length=512, null=True, verbose_name='Cloudinary URL'),
        ),
        migrations.AlterField(
            model_name='interviewanswer',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text="Durée de l'enregistrement en secondes", null=True, verbose_name='Durée (secondes)'),
        ),
        migrations.AlterField(
            model_name='interviewanswer',
            name='video_file',
            field=models.FileField(blank=True, help_text='Réponse vidéo du candidat (legacy, si pas sur Cloudinary)', null=True, upload_to='interview_answers/%Y/%m/%d/', verbose_name='Fichier vidéo (local)'),
        ),
    ]
