# Generated by Django 5.2.5 on 2025-09-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0010_interviewanswer_cloudinary_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewcampaign',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='interviewcampaign',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début'),
        ),
    ]
