# Generated by Django 5.2.5 on 2025-09-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0011_alter_interviewcampaign_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='question_type',
            field=models.CharField(choices=[('technique', 'Technique'), ('comportementale', 'Comportementale'), ('generale', 'Générale')], default='generale', max_length=20, verbose_name='Type de question'),
        ),
    ]
