# Generated by Django 5.2.5 on 2025-09-08 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0012_interviewquestion_question_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription', models.TextField(blank=True, help_text='Texte transcrit de la vidéo via Whisper', null=True, verbose_name='Transcription')),
                ('ai_score', models.FloatField(blank=True, help_text="Score généré par l'IA (0-100)", null=True, verbose_name='Score IA')),
                ('ai_feedback', models.TextField(blank=True, help_text="Commentaires détaillés générés par l'IA", null=True, verbose_name='Feedback IA')),
                ('ai_provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('huggingface', 'Hugging Face'), ('openai', 'OpenAI')], help_text="Service IA utilisé pour l'évaluation", max_length=20, verbose_name='Fournisseur IA')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours de traitement'), ('completed', 'Terminée'), ('failed', 'Échec')], default='pending', max_length=20, verbose_name='Statut')),
                ('expected_skills', models.JSONField(default=list, help_text='Liste des compétences à évaluer', verbose_name='Compétences attendues')),
                ('processing_time', models.FloatField(blank=True, help_text='Durée totale du traitement IA', null=True, verbose_name='Temps de traitement (secondes)')),
                ('error_message', models.TextField(blank=True, help_text="Détails de l'erreur en cas d'échec", null=True, verbose_name="Message d'erreur")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de completion')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Candidat')),
                ('interview_answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_evaluation', to='interviews.interviewanswer', verbose_name="Réponse d'entretien")),
            ],
            options={
                'verbose_name': 'Évaluation IA',
                'verbose_name_plural': 'Évaluations IA',
                'ordering': ['-created_at'],
            },
        ),
    ]
