# Generated by Django 5.2.5 on 2025-09-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0016_add_application_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='interviews__recipie_d337ff_idx',
            old_name='interviews_notificat_recipie_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='interviews__recipie_9a4d65_idx',
            old_name='interviews_notificat_recipie_is_read_idx',
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='communication_feedback',
            field=models.TextField(blank=True, help_text='Commentaires sur la communication', null=True, verbose_name='Feedback Communication'),
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='communication_score',
            field=models.FloatField(blank=True, help_text='Score de communication (0-100): clarté, fluidité, structure', null=True, verbose_name='Score Communication'),
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='confidence_feedback',
            field=models.TextField(blank=True, help_text="Commentaires sur la confiance et l'assurance", null=True, verbose_name='Feedback Confiance'),
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text="Score de confiance/assurance (0-100): ton affirmatif, peu d'hésitation", null=True, verbose_name='Score Confiance'),
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='relevance_feedback',
            field=models.TextField(blank=True, help_text='Commentaires sur la pertinence de la réponse', null=True, verbose_name='Feedback Pertinence'),
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='relevance_score',
            field=models.FloatField(blank=True, help_text='Score de pertinence (0-100): réponse alignée avec la question', null=True, verbose_name='Score Pertinence'),
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='technical_scores',
            field=models.JSONField(default=dict, help_text='Scores par compétence technique {compétence: {score: float, feedback: str}}', verbose_name='Scores techniques'),
        ),
        migrations.AlterField(
            model_name='aievaluation',
            name='ai_feedback',
            field=models.TextField(blank=True, help_text="Commentaires détaillés générés par l'IA", null=True, verbose_name='Feedback IA global'),
        ),
        migrations.AlterField(
            model_name='aievaluation',
            name='ai_score',
            field=models.FloatField(blank=True, help_text="Score global généré par l'IA (0-100)", null=True, verbose_name='Score IA global'),
        ),
    ]
