# Generated by Django 5.2.5 on 2025-09-09 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0019_recruiterevaluation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalInterviewEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_skills', models.FloatField(blank=True, help_text='Évaluation des compétences techniques démontrées', null=True, verbose_name='Compétences techniques (0-100)')),
                ('communication_skills', models.FloatField(blank=True, help_text="Clarté, fluidité, capacité d'expression", null=True, verbose_name='Compétences de communication (0-100)')),
                ('problem_solving', models.FloatField(blank=True, help_text='Approche analytique et logique', null=True, verbose_name='Résolution de problèmes (0-100)')),
                ('cultural_fit', models.FloatField(blank=True, help_text="Alignement avec les valeurs de l'entreprise", null=True, verbose_name='Adéquation culturelle (0-100)')),
                ('motivation', models.FloatField(blank=True, help_text="Intérêt pour le poste et l'entreprise", null=True, verbose_name='Motivation (0-100)')),
                ('overall_score', models.FloatField(blank=True, help_text='Score global calculé ou saisi par le recruteur', null=True, verbose_name='Score global (0-100)')),
                ('final_recommendation', models.CharField(blank=True, choices=[('hire', 'Embaucher immédiatement'), ('second_interview', 'Convoquer pour un 2ème entretien'), ('consider', 'À considérer'), ('reject_politely', 'Rejeter poliment'), ('reject', 'Rejeter définitivement')], max_length=20, null=True, verbose_name='Recommandation finale')),
                ('strengths', models.TextField(blank=True, help_text="Points forts identifiés durant l'entretien", null=True, verbose_name='Points forts')),
                ('weaknesses', models.TextField(blank=True, help_text="Axes d'amélioration ou faiblesses constatées", null=True, verbose_name="Points d'amélioration")),
                ('general_comments', models.TextField(blank=True, help_text='Impression générale et commentaires libres', null=True, verbose_name='Commentaires généraux')),
                ('next_steps', models.TextField(blank=True, help_text='Actions recommandées suite à cet entretien', null=True, verbose_name='Prochaines étapes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('job_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='global_evaluation', to='interviews.jobapplication', verbose_name='Candidature')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Recruteur évaluateur')),
            ],
            options={
                'verbose_name': "Évaluation Globale d'Entretien",
                'verbose_name_plural': "Évaluations Globales d'Entretien",
                'ordering': ['-created_at'],
                'unique_together': {('job_application', 'recruiter')},
            },
        ),
    ]
