# Generated by Django 5.2.5 on 2025-09-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0020_globalinterviewevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterevaluation',
            name='global_score',
            field=models.FloatField(blank=True, help_text="Score global pour l'ensemble de l'entretien du candidat", null=True, verbose_name='Score Global Entretien (0-100)'),
        ),
        migrations.DeleteModel(
            name='GlobalInterviewEvaluation',
        ),
    ]
