# Generated by Django 5.2.5 on 2025-09-10 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0022_add_globalinterviewevaluation_with_candidate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalinterviewevaluation',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_global_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Candidat évalué'),
        ),
        migrations.AlterField(
            model_name='globalinterviewevaluation',
            name='communication_skills',
            field=models.FloatField(blank=True, help_text='Clarté, écoute, expression', null=True, verbose_name='Compétences Communication'),
        ),
        migrations.AlterField(
            model_name='globalinterviewevaluation',
            name='cultural_fit',
            field=models.FloatField(blank=True, help_text="Alignement avec les valeurs de l'entreprise", null=True, verbose_name='Adéquation Culturelle'),
        ),
        migrations.AlterField(
            model_name='globalinterviewevaluation',
            name='final_recommendation',
            field=models.CharField(blank=True, choices=[('hire_immediately', 'Embaucher immédiatement'), ('second_interview', 'Deuxième entretien'), ('consider', 'À considérer'), ('reject_politely', 'Refuser poliment'), ('reject_definitively', 'Refuser définitivement')], max_length=30, null=True, verbose_name='Recommandation finale'),
        ),
        migrations.AlterField(
            model_name='globalinterviewevaluation',
            name='general_comments',
            field=models.TextField(blank=True, help_text='Impression générale et observations', null=True, verbose_name='Commentaires généraux'),
        ),
        migrations.AlterField(
            model_name='globalinterviewevaluation',
            name='motivation',
            field=models.FloatField(blank=True, help_text="Intérêt pour le poste et l'entreprise", null=True, verbose_name='Motivation'),
        ),
        migrations.AlterField(
            model_name='globalinterviewevaluation',
            name='next_steps',
            field=models.TextField(blank=True, help_text='Actions recommandées', null=True, verbose_name='Prochaines étapes'),
        ),
        migrations.AlterField(
            model_name='globalinterviewevaluation',
            name='overall_score',
            field=models.FloatField(blank=True, help_text='Score global calculé automatiquement', null=True, verbose_name='Score Global'),
        ),
        migrations.AlterField(
            model_name='globalinterviewevaluation',
            name='problem_solving',
            field=models.FloatField(blank=True, help_text='Analyse, créativité, logique', null=True, verbose_name='Résolution de Problèmes'),
        ),
        migrations.AlterField(
            model_name='globalinterviewevaluation',
            name='strengths',
            field=models.TextField(blank=True, help_text='Points positifs identifiés', null=True, verbose_name='Points forts'),
        ),
        migrations.AlterField(
            model_name='globalinterviewevaluation',
            name='technical_skills',
            field=models.FloatField(blank=True, help_text='Maîtrise technique et expertise métier', null=True, verbose_name='Compétences Techniques'),
        ),
        migrations.AlterField(
            model_name='globalinterviewevaluation',
            name='weaknesses',
            field=models.TextField(blank=True, help_text="Axes d'amélioration identifiés", null=True, verbose_name='Points faibles'),
        ),
        migrations.AlterField(
            model_name='recruiterevaluation',
            name='candidate',
            field=models.ForeignKey(help_text="Candidat qui passe l'entretien", on_delete=django.db.models.deletion.CASCADE, related_name='received_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='Candidat évalué'),
        ),
    ]
