# Generated by Django 5.2.5 on 2025-09-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0023_alter_globalinterviewevaluation_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'En cours'), ('accepted', 'Acceptées'), ('rejected', 'Refusées')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
