# Generated by Django 5.2.5 on 2025-09-15 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0024_alter_jobapplication_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AiEvaluation',
        ),
    ]
