# Generated by Django 5.2.5 on 2025-09-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0026_remove_recruiterevaluation_global_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterevaluation',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellente réponse'), ('good', 'Bonne réponse'), ('average', 'Réponse moyenne'), ('below_average', 'Réponse faible'), ('poor', 'Réponse insuffisante')], max_length=20, null=True, verbose_name='Recommandation pour cette réponse'),
        ),
    ]
