# Generated by Django 5.2.5 on 2025-09-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0028_aievaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'En cours'), ('technical_interview', 'Entretien technique programmé'), ('accepted', 'Acceptées'), ('rejected', 'Refusées')], default='pending', max_length=20, verbose_name='Statut'),
        ),
    ]
