# Generated by Django 5.2.5 on 2025-09-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0029_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlink',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de completion'),
        ),
        migrations.AddField(
            model_name='campaignlink',
            name='status',
            field=models.CharField(choices=[('active', 'Actif'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('abandoned', 'Abandonné')], default='active', max_length=20, verbose_name="Statut de l'entretien"),
        ),
    ]
