# Generated by Django 5.2.5 on 2025-08-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('USER', 'Utilisateur Standard')], default='USER', max_length=50),
        ),
    ]
