# Generated by Django 5.2.5 on 2025-08-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('RECRUTEUR', 'Recruteur'), ('CANDIDAT', 'Candidat')], default='CANDIDAT', max_length=50),
        ),
    ]
