# Generated by Django 5.2.5 on 2025-08-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_role'),
        ('users', '0003_convert_user_roles'),
    ]

    operations = [
    ]
