# Generated by Django 5.2.5 on 2025-09-09 13:12
# This migration is a no-op since fields were already added in 0005_add_profile_fields_safe

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_profile_fields_safe'),
    ]

    operations = [
        # No operations needed - fields already added safely in previous migration
    ]
