# Generated by Django 5.2.5 on 2025-09-09 18:57
# This migration is a no-op since fields were already added in 0005_add_profile_fields_safe

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_address_customuser_bio_customuser_city_and_more'),
    ]

    operations = [
        # No operations needed - fields already added safely in previous migration
    ]
