# Generated by Django 5.2.5 on 2025-09-10 12:00
# This migration is a no-op since fields were already added in previous migrations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_address_customuser_bio_customuser_city_and_more'),
    ]

    operations = [
        # No operations needed - fields already added in previous migrations
    ]
