# Generated by Django 5.2.5 on 2025-09-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_address_customuser_bio_customuser_city_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='customuser',
        #     name='address',
        #     field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse'),
        # ),
        # Tous les champs existent déjà, migration vide
        # migrations.AddField(...) commentés car les champs existent déjà
    ]
