# Generated by Django 5.2.5 on 2025-09-10 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_address_customuser_bio_customuser_city_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='customuser',
        #     name='address',
        # ),
        # Migration vide car le champ 'address' n'existe pas dans le modèle
    ]
