# Generated by Django 5.2.5 on 2025-09-10 13:09

from django.db import migrations, models


def safe_add_fields(apps, schema_editor):
    """Safely add fields that don't already exist"""
    from django.db import connection
    
    CustomUser = apps.get_model('users', 'CustomUser')
    
    # Check existing columns
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name='users_customuser'
        """)
        existing_columns = [row[0] for row in cursor.fetchall()]
    
    # Only add fields that don't exist
    fields_to_add = [
        ('bio', models.TextField(blank=True, null=True, verbose_name='Présentation')),
        ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
        ('country', models.CharField(default='Maroc', max_length=100, verbose_name='Pays')),
        ('current_position', models.CharField(blank=True, max_length=200, null=True, verbose_name='Poste actuel')),
        ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
        ('education_level', models.CharField(blank=True, choices=[('BAC', 'Baccalauréat'), ('BAC+2', 'BAC+2'), ('BAC+3', 'BAC+3 (Licence)'), ('BAC+5', 'BAC+5 (Master)'), ('BAC+8', 'BAC+8 (Doctorat)')], max_length=20, null=True, verbose_name="Niveau d'éducation")),
        ('experience_years', models.CharField(blank=True, choices=[('0-1', '0-1 an'), ('1-3', '1-3 ans'), ('3-5', '3-5 ans'), ('5-10', '5-10 ans'), ('10+', 'Plus de 10 ans')], max_length=20, null=True, verbose_name="Années d'expérience")),
        ('github_profile', models.URLField(blank=True, null=True, verbose_name='Profil GitHub')),
        ('linkedin_profile', models.URLField(blank=True, null=True, verbose_name='Profil LinkedIn')),
        ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
        ('portfolio_url', models.URLField(blank=True, null=True, verbose_name='Portfolio/Site web')),
        ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code postal')),
        ('profile_updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour du profil')),
        ('skills', models.TextField(blank=True, null=True, verbose_name='Compétences')),
    ]
    
    for field_name, field in fields_to_add:
        if field_name not in existing_columns:
            try:
                schema_editor.add_field(CustomUser, field)
            except Exception as e:
                print(f"Warning: Could not add field {field_name}: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_customuser_address'),
    ]

    operations = [
        migrations.RunPython(
            safe_add_fields,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
