# Generated by Django 5.2.5 on 2025-09-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_bio_customuser_city_customuser_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Présentation'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(default='Maroc', max_length=100, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Poste actuel'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='education_level',
            field=models.CharField(blank=True, choices=[('BAC', 'Baccalauréat'), ('BAC+2', 'BAC+2'), ('BAC+3', 'BAC+3 (Licence)'), ('BAC+5', 'BAC+5 (Master)'), ('BAC+8', 'BAC+8 (Doctorat)')], max_length=20, null=True, verbose_name="Niveau d'éducation"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience_years',
            field=models.CharField(blank=True, choices=[('0-1', '0-1 an'), ('1-3', '1-3 ans'), ('3-5', '3-5 ans'), ('5-10', '5-10 ans'), ('10+', 'Plus de 10 ans')], max_length=20, null=True, verbose_name="Années d'expérience"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='github_profile',
            field=models.URLField(blank=True, null=True, verbose_name='Profil GitHub'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True, verbose_name='Profil LinkedIn'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True, verbose_name='Portfolio/Site web'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Code postal'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour du profil'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='Compétences'),
        ),
    ]
